### ISSUE TITLE
`delay` should carry an effect label.

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-aff#105]
It should be possible to define `runPureAff :: forall a. Aff () a -> a`, but currently `delay` does not carry an effect.

**Comment by jdegoes** [comment]
No, it should not carry an effect label. The effect of asynchronous computation is subsumed in `Aff` the way the effect of synchronous computation is subsumed in `Eff`. You can create a version of `delay` for `Eff` merely by burning cycles in a `while` loop, as part of computing a throwaway part of an expression. Indeed, `Eff` can be delayed by ordinary synchronous computation, in the same way `Aff` can be delayed by ordinary asynchronous computation.

Now the signature you can promise is: `runSyncPureAff :: forall a. Aff () a -> Maybe a`, which is, if the computation is pure and entirely synchronous, you can compute its value, and not otherwise.

**Comment by natefaubion** [comment]
However, it's not possible to use the JS scheduler in PureScript otherwise (via `Eff`) without introducing some sort of effect.

**Comment by natefaubion** [comment]
For example, I would consider the equivalent Eff a bit disingenuous:

```purescript
delayEff :: forall eff. Eff eff Unit -> Eff eff Unit
```

Because it invokes effects in the run time you would otherwise not expect it to.

**Comment by natefaubion** [comment]
Another option is to have `Aff` introduce an `ASYNC` effect, maybe.

**Comment by jdegoes** [comment]
That's an implementation detail. `delay` has no effect except asynchronous computation, even if you don't grant it's pure (and I would argue that it is pure, in the same way synchronous computation is not considered an effect nor tracked by most type systems), the "effect" of async computation can be considered to be modeled in the type (`Aff`).

Introducing an `ASYNC` effect doesn't really help since people can and do import their own `Aff` functions from Javascript. At least in the current version of `Aff`, so most real `Aff` code in the wild doesn't declare a "async computation" effect.

The reality is that `runPureAff` cannot promise to run any `Aff`, and while you could probably get there with effect labels, it would require a lot of updates to code in the wild and that's not consistent with `Eff` (which has no `sync :: SYNC` effect.

This function here can be implemented trivially in a type safe way:

```haskell
delayEff :: forall eff. Eff eff Unit -> Eff eff Unit
```

Just compute a list of the first 1000 primes, and return the same computation. The computation will be delayed by a really long time. Yet the type signature won't have changed, nor will the effect row.

Effect rows can't reliably track things like how long it will be until you get the value. I think it's a mistake trying to pretend that with `Aff`. And why do it, anyway? You can already trampoline pure computations and run the trampoline without co-opting `Aff` for that purpose.

**Comment by natefaubion** [comment]
It's somewhat contrived, but it prevents you from writing a zero-copy `runSTArray`. Given the signature:

```purescript
-- Note the closed effect row, indicating no other effects.
pureSTArray :: forall a. (forall h. Eff (st :: ST h) (STArray h a)) -> Array a
```

We would assume its possible to avoid the array copy, however, we can subvert this using `Aff`.

```purescript
myArray :: Array Int
myArray = pureSTArray do
  ref <- newSTArray
  runAff
    (const (pure unit))
    (const (pushSTArray ref 42))
    (delay (Milliseconds 100.0))
  pure ref
```

**Comment by natefaubion** [comment]
Now, it can also be argued `ST` should not be an effect, but a newtype.

**Comment by natefaubion** [comment]
I think that it's fair to say that delay is not effectful _within_ `Aff` (just as `SYNC` doesn't make sense _within_ `Eff`), but Aff and Eff aren't semantically identical, and whereas scheduling is baked into the semantics of Aff, it is _not_ baked into the semantics of Eff. It's easy to observe this through otherwise sensible APIs (like the above `pureSTArray`). So I disagree, and I think it makes sense to introduce a new effect by launching an `Aff`.

**Comment by natefaubion** [comment]
Or another way to put it, `runAff` interprets `Aff` into `Eff` which may introduce other constrains on `Eff` that are otherwise implicit within `Aff`, namely asynchronous scheduling.

**Comment by jdegoes** [comment]
All I have to do in order to introduce "asynchronous scheduling" is call `makeAff`. What you want is tracking the terms of the `Aff` sum used in construction of an `Aff`, which is not unlike phantom types. Unless there is more to this than "co-opting Aff for trampolining", I don't see the point, especially since you can't guarantee these constraints in the wild. Like all effect labels, they're user-defined comments at best.
