### ISSUE TITLE
Exceptions can't be caught after an interrupt

### ISSUE THREAD

**Issue by natefaubion** [slamdata/purescript-aff#113]
If a fiber is killed, then exceptions can no longer be caught during finalization. This is because the interrupt is naively taking precedence over all exception handlers.

**Comment by jdegoes** [comment]
In my version, killing a fiber runs the finalizers but failure of finalizers is not reflected in the return value of killing. This is partially because there may be `n` finalizers, each one of which may fail, but that cannot impact the guarantee of the other finalizers to be run, which means at minimum, you would need to collect all the errors produced during finalization and return an aggregate of them when resuming the kill attempt. Instead, I just guarantee `kill` cannot die and ignore finalizer errors.

Not convinced swallowing errors is correct, but the guarantees prevent one finalizer error from impacting the running of others.

**Comment by natefaubion** [comment]
@jdegoes Did you mean to put that in #110?

What I'm referring to is something like

```purescript
example = do
  fiber ← forkAff $ bracket
    (delay (Milliseconds 10.0))
    (\_ → throwError (error "Finalizer") `catchError` \_ → log "Caught!")
    (\_ → pure unit)
  killFiber (error "Nope") fiber
```

The "Finalizer" exception will not currently be caught due to this bug. It will instead be rethrown in a fresh stack.

**Comment by natefaubion** [comment]
Basically, `catchError` does not work if it's being run during a finalizer as part of an interrupt.

**Comment by natefaubion** [comment]
A related issue is that if you put a `generalBracket` inside a finalizer, it will always be called with the `killed` branch.
