### ISSUE TITLE
generalize Aff.Console functions to MonadAff

### ISSUE THREAD

**Issue by matthewleon** [slamdata/purescript-aff#143]
Example:

```purescript
log :: forall eff. String -> Aff (console :: CONSOLE | eff) Unit
```

becomes

```purescript
log :: forall eff m. MonadAff m => String -> m (console :: CONSOLE | eff) Unit
```

**Comment by matthewleon** [comment]
Perhaps this is unnecessary, and the right thing is to just provide lifted console functions for `MonadEff` in a separate lib. Feel free to close if you think that's the way to go.

**Comment by safareli** [comment]
I think it would be better to use MonadEff

`log :: forall eff m. MonadEff m => String -> m (console :: CONSOLE | eff) Unit`

as we are using `liftEff` so no need for `MonadAff`.

But we could also use `MonadEff m` in purescript-console instead of direct `Eff` usage, and just remove Aff.Console module. so maybe it's worth opening issue in purescript-console?

**Comment by garyb** [comment]
That sounds fine - I'd suggested doing something similar in the past, but it was pointed out that using the constrained approach does introduce some overhead, so we'd probably want to continue providing the monomorphic versions too. But yes, it should just be `MonadAff` constrained, and we can just remove them from here entirely.

**Comment by safareli** [comment]
`MonadAff` constrained you mean `MonadEff`?

**Comment by matthewleon** [comment]
https://pursuit.purescript.org/packages/purescript-console-lifted/0.0.1/docs/ConsoleLifted

feel free to close

**Comment by Thimoteus** [comment]
There's [these](https://pursuit.purescript.org/packages/purescript-console/4.1.0/docs/Effect.Class.Console) now for 0.12.
