### ISSUE TITLE
Bracket aquire function gets killed

### ISSUE THREAD

**Issue by felixSchl** [slamdata/purescript-aff#170]
I am experiencing some very odd behavior, to say the least. Unfortunately, I am of yet unable to reproduce this issue in a small test case, but I am still working on it so I'll have to just report the symptoms for the time being.

We are observing the acquire part of a bracket getting killed part way through it *and* the clean up handler running. Because the acquire handler had not finished running, the clean up handler gets an "undefined" value passed in, causing all sorts of trouble.

Hopefully I can recreate this in a small test case, but the outlook is rather grim.

**EDIT**: Using the code from #169 the error goes away, but the fiber never gets killed at all.

**Comment by natefaubion** [comment]
Note, that all #169 does is change where async scheduling occurs. Async boundaries get put into a scheduler to ensure fairness. Currently, async scheduling happens when an async action _resolves_. This means that the async effect will be run promptly, but once the callback is invoked, it won't necessarily start evaluating the next part of the Aff. This can be problematic in practice, because even though someone has called the callback , the fiber is at the mercy of the scheduler, and can still be killed. This can cause all sorts of _very_ subtle bugs and ultimately breaks a useful level of reasoning (I called the callback to complete, but it still got killed). That PR switches it so that a fiber gets scheduled _before_ the effect is run, and resolution is immediate. This can _definitely_ change the order of effect evaluation. If code has been written that relies an a specific ordering of effects among forked fibers, then it will very likely break.

**Comment by felixSchl** [comment]
I have managed to reproduce the problem:

```purescript
module Test.Main
  ( main
  ) where

import Prelude

import Control.Monad.Error.Class (try)
import Control.Monad.Fork.Class (bracket)
import Control.Monad.Rec.Class (forever)
import Control.Parallel (parSequence_)
import Data.Maybe (Maybe(..))
import Data.Time.Duration (Milliseconds(..))
import Debug.Trace (traceM)
import Effect (Effect)
import Effect.Aff (delay)
import Effect.Class (liftEffect)
import Effect.Exception (throwException)
import Effect.Exception as Error
import Test.Spec (describe, it)
import Test.Spec.Reporter (consoleReporter)
import Test.Spec.Runner as Spec

main :: Effect Unit
main = Spec.run' (Spec.defaultConfig { timeout = Just 100000 }) [consoleReporter] do
  describe "..." $ it "..." $ do
    void $ try $ parSequence_
      [ void $
          bracket
            (do
               traceM "a"
               traceM =<<
                 bracket
                  (pure unit)
                  (\cond _ -> pure unit)
                  (\_ -> delay $ 500.0 # Milliseconds)
               traceM "b"
            )
            (\_ _ -> pure unit)
            (\_ -> forever $ delay $ 5.0 # Milliseconds)
      , do
          delay $ 10.0 # Milliseconds
          traceM "crashing..."
          liftEffect $ throwException $ Error.error "crash"
      ]

    traceM "waiting..."
    delay $ 1000.0 # Milliseconds
    traceM "done"
```

this test produces the following output:

```
'a'
'crashing...'
'waiting...'
'done'
```

note the absence of 'b' in the output

**Comment by natefaubion** [comment]
Here's a reduced regression test:

```purescript
test_regression_bracket_kill_mask ∷ Aff Unit
test_regression_bracket_kill_mask = assert "regression/kill-bracket-mask" do
  ref ← newRef []
  let
    action s =
      void $ modifyRef ref (_ <> [ s ])
  fiber ← forkAff do
    bracket
      do
        action "a"
        bracket
          (pure unit)
          (const (pure unit))
          (\_ -> delay (Milliseconds 10.0))
        action "b"
      (const (pure unit))
      (\_ -> delay (Milliseconds 10.0))
  delay (Milliseconds 5.0)
  killFiber (error "nope") fiber
  liftEffect <<< Console.logShow =<< readRef ref
  readRef ref <#> eq
    [ "a"
    , "b"
    ]
```
