### ISSUE TITLE
Progress reporting

### ISSUE THREAD

**Issue by zudov** [slamdata/purescript-aff#42]
I didn't give it much thought, but it probably would be useful if `Aff` computations had some way of reporting their progress (like promises do).

Was such feature considered?

**Comment by jdegoes** [comment]
Yes, and I think it makes the most sense as a third-party library. The reason is that if you bake it into `Aff`, it will impose performance overhead for every use case. Instead, by layering the feature on top of `Aff`, it will impose performance overhead only when it's actually used.

The API for such a library could be quite simple, something like:

```haskell
newtype Progress = Progress Double

type Thread e = { cancel :: Canceler e, progress :: Aff e Progress }

data ProgressAff = ...

forkAffWithProgress :: forall e a. ProgressAff e a -> Aff e (Thread e)

makeAffWithProgress :: forall e a. ((Progress -> Aff e a) -> ...) -> ProgressAff e a
```

Then to use progress, you make a `ProgressAff`, which calls the "set progress" function to report on progress, and client code kicks off the `ProgressAff` and has some means to check progress (or maybe get notified on progress changes, either way).

**Comment by paf31** [comment]
Consider using `aff-coroutines` for this, perhaps.

**Comment by jdegoes** [comment]
Yeah, a coroutine that emits the progress values, and then returns its final monadic result, might work too. :+1:

**Comment by zudov** [comment]
Thanks for explanation. Yes, that makes a lot of sense not to include it into the main library, and well, `purescript-aff-coroutines` pretty much provides it already.
