### ISSUE TITLE
Move as much FFI into PS as possible

### ISSUE THREAD

**Issue by texastoland** [slamdata/purescript-aff#70]
Placeholder for brainstorming. @spicydonuts brought this to my attention a couple months ago and I have some bandwidth to attempt it.

**Comment by natefaubion** [comment]
I think `forkAll` can move to PS because the `MonadRec` instance no longer bounces.

**Comment by jdegoes** [comment]
Moving stuff into PS will generally make it slower. I suggest writing a benchmark so we can gauge the tradeoffs involved.

If performance were no issue, I'd model `Aff` like this:

```purescript
type CallbackFn e a = (Either Error a -> Eff e Unit) -> Eff e (Canceler e)

data Aff e a = Sync (Eff e a) | Async (CallbackFn e a)

type Canceler e = Lazy (Aff e Boolean)

data AVar a = AVar (Ref (Either a (List (forall r. (Either Error a -> Eff (avar :: AVAR | r) Unit)))))
```

I'd be open to such a pure implementation if the performance degradation was not terrible.

**Comment by texastoland** [comment]
Would you recommend somewhere to look to model such a benchmark? I guess anything [using Benchotron](https://libraries.io/bower/purescript-benchotron/dependent-repositories)? I intend to at least scrutinize generated JS.

**Comment by jdegoes** [comment]
First start: Do a loop of 10000 binds, each of which does a map and a pure. Something like:

```haskell
loop n = if n == 0 then pure 1 else (_ * 2) <$> loop (n - 1)

test = loop 10000
```

Or its tail-rec equivalent.

**Comment by natefaubion** [comment]
I've written a version of `Aff` using `Free` which is 100% PS, and I think the overhead is acceptable. Additionally, all the dispatch is in a single interpreter and it is _always_ stack-safe under monadic recursion (no need for `MonadRec`). It's hard to actually come up with a test that stresses it in a meaningful way (the one provided above does not work because it isn't stack safe, and can't be done with `tailRecM` in a way that preserves what we actually want to test). In any case, what I've tested is maybe about half the speed. This is only relevant if you are writing Aff code that is 99% synchronous looping though, which is why I think it's fine.

**Comment by jdegoes** [comment]
It needs benchmarks for several cases, including flat and shallow binds, etc. Given how many people are using `Aff`, we can't afford a performance regression, so any fundamental change in the architecture needs to ship with benchmarks against the old "bare metal" approach.

**Comment by natefaubion** [comment]
Do you consider "bare-metal" to be the current implementation, or the one you suggested above? The one you suggested above isn't very interesting because if you try to write a `Bind` instance for it, everything necessarily becomes `Async`, so there's no point in separating the two. Separating the two in a meaningful way involves re-implementing an ad-hoc version of `Free` anyway. As usual it's the case that the bind/interpreter overhead is meaningless as soon as something goes async, so microbenching synchronous binds isn't terrible important to me. It is important to me that the current implementation is basically understood by no one because it's a hodge-podge of terrible FFI hacks to get around real issues with the representation.

**Comment by natefaubion** [comment]
I've tried implemented it using an ad hoc `Free` baked into the representation. This is more efficient than the proper `Free` version (though slower than the JS representation, but only by about 60%). The implementation is fairly hairy (and somewhat unsafe) since it mixes in things that `Free` would take care of for you. It's always stack-safe, even in the presence of `attempt`. You can see the example implementation [here](https://gist.github.com/natefaubion/375bf1d43a2e41cdf1f21beadbf6a2b1).

**Comment by jdegoes** [comment]
The current Javascript solution is "bare metal", although I know how to speed it up significantly by going "ad hoc free" in Javascript with a custom interpreter, so maybe it's not really bare metal. 😄 

The performance of synchronous code is crucially important since usually a single async effect will be followed by numerous sync effects in real-life code. You can't do anything about the bad performance of async, but you can at least batch and make the synchronous sections very fast.

I agree that the current code needs improvement, but we can't replace it with something that's 60% slower. If anything, I'd prefer replacing it with something that's easier to maintain and 60% faster.

Your gist is the right direction, I think you should be able to make this same approach much faster (faster than existing `Aff`). In particular, rewriting `drainAff` (the main interpreter) in Javascript to eliminate the numerous allocations and function calls (also the interpreter can be simplified, and this version doesn't implement canceling, etc.). I think it's probably 20 hours of work to take this to the point where the code is saner, it's faster than `Aff`, and it provides stronger guarantees (no stack overflows ever, etc.).

**Comment by natefaubion** [comment]
FWIW, `drainAff` is written in such a way to minimize allocations. By using ST exclusively (unboxed reference cells), fully saturated constructors (no currying), and inlining all the branches (no extra thunks), it generates optimal JS. https://gist.github.com/natefaubion/99b40e0bc10464c01ad759bb6fa313be

What are your ideas for simplifying the interpreter? I believe that these states are required to handle Aff edge-cases.

**Comment by natefaubion** [comment]
One thing that a native JS solutions would do is remove nested property access (I wish the PS compiler wasn't so liberal about inlining these references).

**Comment by natefaubion** [comment]
> but you can at least batch and make the synchronous sections very fast

I don't think it's as simple as that. Every `Sync` action must be guarded against, because with `AVars` its possible for a thread to get a reference to it's own canceler (in the real world, this would likely be transitively). If you indiscriminately batch sync calls, then it's possible for a thread to not actually cancel. This is why I've run everything through the same loop.

Part of the problem I have with the current representation is I'm fairly certain there is quite a bit of incorrect behavior (if under unlikely, but _very_ hard to debug code paths, especially wrt to edge cases in cancellation), but it's impossible to tell since no one can reason about it. I'm not convinced a truly correct implementation will be faster than what we have now.

**Comment by jdegoes** [comment]
> What are your ideas for simplifying the interpreter? I believe that these states are required to handle Aff edge-cases.

The happy path through the interpreter should have zero allocations and minimal function applications.

The compiled JS looks much more efficient than I assumed it would be (thanks to the inlining), but you still have numerous unnecessary allocations and some unnecessary function applications.

I can show you a version in Scala I wrote that achieves this.

> I don't think it's as simple as that.

You are already batching them, in the sense that synchronous actions will be executed in the main loop, one after the other. This is thanks to your `Sync (Eff eff (Either Error a))` case (which I think should be simplified to `Sync (Eff eff a)`). Original `Aff` does no "batching" and every synchronous action is converted into a continuation, which adds unnecessary overhead.

> I'm not convinced a truly correct implementation will be faster than what we have now.

Sure it can be, I've already written it, albeit for Scala not PureScript. 😄

**Comment by natefaubion** [comment]
> Sure it can be, I've already written it, albeit for Scala not PureScript.

I have translated my PS code to JS, and removed the allocations for steps, and it is indeed 2x as fast as the current implementation.

**Comment by natefaubion** [comment]
https://gist.github.com/natefaubion/8cae9ef8aa74e85c825a90ee9fed4ba8

**Comment by natefaubion** [comment]
> Very nice, that should bring into the realm of Aff. It's possible to go faster but not really necessary for this issue. Can you show the code yet?

Do you mean `Eff`? I mean that it's 2x faster than `master`.

**Comment by jdegoes** [comment]
> Do you mean Eff? I mean that it's 2x faster than master.

If you're 2x faster than `Aff` with a good / useful benchmark, then I'm all for merging this as-is (I thought you meant 2x faster than the older slower approach). Although looking at the Javascript, I cannot convince myself the exception handling is correct — what's the logic for this?

**Comment by natefaubion** [comment]
> Although looking at the Javascript, I cannot convince myself the exception handling is correct — what's the logic for this?

Which part exactly? The canceler? It's not correct, because it depends on clarification in #104. Otherwise it depends on the lack of a `MonadCont` instance. If a continuation can't be invoked more than once, then we only need to track the pending canceler within `status`. As far as catching `Eff`, I wanted to look at restricting the `MonadEff` instance via a `RowLacks` constaint, which would prevent the user from lifting an Eff that carries an `exception` effect.

**Comment by natefaubion** [comment]
> If you're 2x faster than Aff with a good / useful benchmark, then I'm all for merging this as-is (I thought you meant 2x faster than the older slower approach).

It's hard to write a useful benchmark because pathological cases easily blow the stack with the current `Aff` 😆. It necessitates using `tailRecM` which forces everything to be largely be right-associative. But, it's just a large `tailRecM` count-down with a bunch of binds and pures mixed in with the loop so as to introduce the usual `bind` overhead with the existing `Aff`. I've tested both with and without `tailRecM` (on a suitable scale so it doesn't blow the stack), and the new version is faster in all regards.

**Comment by natefaubion** [comment]
Also `tailRecM` is probably the fastest part of the current `Aff`. With synchronous binds, it's just a hot loop. `tailRecM` is the slowest part of the new `Aff` (since it just introduces more binds), and it's still faster.

**Comment by natefaubion** [comment]
Here is what I'm benching (suggestions welcome):

```purescript
loopAff ∷ ∀ eff. Int → Aff.Aff eff Int
loopAff = tailRecM go
  where
  go n
    | n <= 0    = pure $ Done n
    | otherwise = do
        _ ← do
          _ ← do
            _ ← pure n
            _ ← pure n
            _ ← pure n
            pure n
          _ ← pure n
          _ ← pure n
          _ ← pure n
          pure n
        pure $ Loop (n - 1)

loopFreeLN ∷ ∀ eff. Int → FreeLN.Aff eff Int
loopFreeLN = go
  where
  go n
    | n <= 0    = pure n
    | otherwise = do
        _ ← do
          _ ← do
            _ ← pure n
            _ ← pure n
            _ ← pure n
            pure n
          _ ← pure n
          _ ← pure n
          _ ← pure n
          pure n
        loopFreeLN (n - 1)

main ∷ Eff (console ∷ Console.CONSOLE) Unit
main = do
  bench \_ → runPure (Aff.runAff (const (pure unit)) (const (pure unit)) $ loopAff 10000)
  bench \_ → runPure (FreeLN.runAff (const (pure unit)) $ loopFreeLN 10000)
```
```
mean   = 17.68 ms
stddev = 947.65 μs
min    = 16.99 ms
max    = 25.50 ms

mean   = 9.36 ms
stddev = 801.01 μs
min    = 8.70 ms
max    = 14.75 ms
```

**Comment by jdegoes** [comment]
I'd try this one:

```haskell
fib :: forall e. Int -> Aff e Int
fib n = if n <= 1 then pure n else do
  a <- fib (n - 1) 
  b <- fib (n - 2)
  pure a + b
```

This creates a large tree that's deep (depending on `n`) and broad, which is a decent test of `bind` and `pure`. I have some other benchmarks for `map`, `attempt`, etc., that I can translate.

**Comment by jdegoes** [comment]
> Which part exactly? 

Does attempting work exactly as exception handling, e.g. extend arbitrarily deep in the call stack, with nested attempts functioning as nested exception handlers?

When interpreting the `Aff` inside an attempt `Aff`, you can go arbitrarily deep in the call stack, before an exception is thrown, and you have to pop back up to the "exception handler" (`Left e` in the continuation of `Aff`). Etc.

**Comment by natefaubion** [comment]
Attempt should work correctly, I think. It suspends the continuation, and then when the thread "complete"s, whether it's successfully or not, it pops the attempt continuation. The part that's wrong is cancellation in the presence of attempt.

**Comment by jdegoes** [comment]
I meant more generally, apart from `fork`, since `attempt` can be used anywhere. It also looks like you're not catching exceptions from `Eff` which can permanently stall async programs built from sync fragments that throw exceptions. It's a good idea to catch these and treat them as errors.

**Comment by natefaubion** [comment]
`attempt` can be used anywhere here. The interpreter maintains two stacks: `binds`, and `attempts`. `binds` is the stack of continuations and `attempts` is the stack of stacks of continuations. Whenever you `attempt`, it conses the current stack of `binds` onto `attempts` and starts a fresh stack of `binds`. When a stack completes, it pops a stack off of `attempts` and resumes. This handles nested attempts from anywhere. What's incorrect is that for cancellation, it merely cancels the active stack, and will still resume if there are more stacks in `attempts`. It should also cancel all remaining stacks (`attempts = null`), per #104. A `fork` is a separate instance of `_drainAff` and has it's own stack state.

> It also looks like you're not catching exceptions from Eff which can permanently stall async programs built from sync fragments that throw exceptions. It's a good idea to catch these and treat them as errors.

Adding `try/catch` into the main interpreter will likely result in an instant de-opt. I would like to try the following (reversed from the current API):

```purescript
instance monadEffAff :: RowLacks "exception" eff => MonadEff (Aff eff) where
  liftEff = unsafeSync <<< map Right

liftEff' :: forall eff a. Eff (exception :: EXCEPTION | eff) ~> Aff eff
liftEff' = unsafeSync <<< catchException (pure <<< Left) <<< map Right
```

Which will prevent an `exception` label from being lifted into the effects. We can do the same thing for `makeAff`. I would like to avoid catching "pure" exceptions like pattern match failures.

**Comment by natefaubion** [comment]
Here are bench results with `fib` (which must be run with a hilariously small number as not to blow the stack).
```purescript
Aff loop:
mean   = 17.85 ms
stddev = 1.05 ms
min    = 17.07 ms
max    = 26.84 ms

Free loop:
mean   = 9.39 ms
stddev = 646.72 μs
min    = 8.79 ms
max    = 14.62 ms

Aff fib:
mean   = 120.88 μs
stddev = 62.42 μs
min    = 101.89 μs
max    = 1.26 ms

Free fib:
mean   = 86.56 μs
stddev = 47.56 μs
min    = 73.97 μs
max    = 1.07 ms
```

Which is still a good 30% faster compared to `master`.

**Comment by natefaubion** [comment]
Playing around with types for a `MonadEff` instance, I think this is actually what we want:

```purescript
instance monadEffAff
  :: EffectRowEquals eff1 (exception :: EXCEPTION | eff2)
  => MonadEff eff1 (Aff eff2) where
  liftEff =
    unsafeSync
      <<< catchException (pure <<< Left)
      <<< map Right
      <<< effTo
```

This ensures that any lifted Eff gets caught, and the `EXCEPTION` label is removed, unlike now which will catch the exception but still propagate the effect label.

**Comment by natefaubion** [comment]
For now, we are still using FFI pervasively.
