### ISSUE TITLE
ParAff does not run thing in Parallel

### ISSUE THREAD

**Issue by garyb** [slamdata/purescript-aff#76]
Exemplified by:

``` purescript
parTraverse (later' 2000 <<< log) ["hello", "goodbye"]
```

:eyes:

**Comment by garyb** [comment]
Actually, something else might be going on here - the above is still broken though.

**Comment by paf31** [comment]
My guess would be that 

```purescript
derive newtype instance applicativeParAff :: Applicative (ParAff e)
```

is wrapping up the superclass instance for `Apply`.

**Comment by garyb** [comment]
Ah interesting, thanks! That does sound suspect. This was driving me a bit crazy, since this works fine:

``` purescript
sequential $ (\x y -> unit) <$> (parallel $ later' 2000 $ log "foo") <*> (parallel $ later' 2000 $ log "bar")
```

What is it we should diallow, deriving newtype instances for any class underneath a normal instance in the hierarchy?

**Comment by garyb** [comment]
That is exactly it, thanks so much!

**Comment by natefaubion** [comment]
I think this is pretty interesting though. I assume what's happening is that, since the dictionary is just coerced, if you ask for an `Applicative` and call `apply`, you'll get the entailed `Apply` instance. The `Apply` instance declared is different than the `Apply` instance you get through entailment on the derived `Applicative`. I'd consider this a bug in newtype deriving.

**Comment by jdegoes** [comment]
💯

**Comment by garyb** [comment]
purescript/purescript#2399
